blueprints/people/models.py
from blueprints.blueprintapp import db

class People(db.Model):
    __tablename__ = 'peoples'

    pid     = db.Column(db.Integer, primary_key=True)
    name    = db.Column(db.String, nullable=False)
    age     = db.Column(db.Integer)
    job     = db.Column(db.String)

    def __repr__(self):
        return f"<People {self.name}, Age: {self.age}"
    
    def get_id(self):
        return self.pid

blueprints/people/routes.py
from flask import request, render_template, redirect, url_for, Blueprint

from blueprints.blueprintapp import db
from blueprints.people.models import People

people = Blueprint('people', __name__, template_folder='templates')

@people.route('/')
def index():
    people = People.query.all()
    return render_template('people/index.html', people=people)


@people.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'GET':
        return render_template('people/create.html')
    elif request.method == 'POST':
        name    = request.form.get('name')
        age     = int(request.form.get('age'))
        job     = request.form.get('job')

        job = job if job != "" else None

        people = People(name=name, age=age, job=job)

        db.session.add(people)
        db.session.commit()

        return redirect(url_for('people.index'))

blueprints/people/templates/people/create.html
{% extends "base.html" %}
{% block title %} Index Page {% endblock %}

{% block content %}
    <h1>This Create Todos</h1>
    <form action="{{ url_for('people.create') }}" method="post">
        <input type="text" name="name" placeholder="Name" required>
        <input type="number" name="age" placeholder="Age">
        <input type="text" name="job" placeholder="Job">
        <input type="submit" name="Create">
    </form>
{% endblock %}

blueprints/people/templates/people/index.html
{% extends "base.html" %}
{% block title %} Index Page {% endblock %}

{% block content %}
    <h1>This People Page</h1>
    <ul>
        {% for person in people %}
            <li>{{ person }}</li>
        {% endfor %}
    </ul>

{% endblock %}