blueprints/todos/models.py
from blueprints.blueprintapp import db

class Todo(db.Model):
    __tablename__ = 'todos'

    tid         = db.Column(db.Integer, primary_key=True)
    title       = db.Column(db.String, nullable=False)
    description = db.Column(db.String)
    done        = db.Column(db.Boolean, nullable=False)

    def __repr__(self):
        return f"<Todo {self.title}, Done: {self.done}"
    
    def get_id(self):
        return self.tid

blueprints/todos/routes.py
from flask import request, render_template, redirect, url_for, Blueprint

from blueprints.blueprintapp import db
from blueprints.todos.models import Todo

todos = Blueprint('todos', __name__, template_folder='templates')

@todos.route('/')
def index():
    todos = Todo.query.all()
    return render_template('todos/index.html', todos=todos)


@todos.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'GET':
        return render_template('todos/create.html')
    elif request.method == 'POST':
        title       = request.form.get('title')
        description = request.form.get('description')
        done        = True if 'done' in request.form.keys() else False

        description = description if description != "" else None

        todo = Todo(title=title, description=description, done=done)

        db.session.add(todo)
        db.session.commit()

        return redirect(url_for('todos.index'))

blueprints/todos/templates/todos/create.html
{% extends "base.html" %}
{% block title %} Index Page {% endblock %}

{% block content %}
    <h1>This Create Todos</h1>
    <form action="{{ url_for('todos.create') }}" method="post">
        <input type="text" name="title" placeholder="Title" required>
        <input type="text" name="description" placeholder="Description">
        <input type="checkbox" name="done">
        <input type="submit" name="Create">
    </form>
{% endblock %}

blueprints/todos/templates/todos/index.html
{% extends "base.html" %}
{% block title %} Index Page {% endblock %}

{% block content %}
    <h1>This Todos Page</h1>
    <ul>
        {% for todo in todos %}
            <li>{{ todo }}</li>
        {% endfor %}
    </ul>

{% endblock %}